In [1]:
import pandas as pd
locations = ["EL", "DL", "LB", "ML", "TS", "NT", "CH", "SS"]

In [2]:
inputfile = "../data/many/nan.csv"
outputfile = "../data/many/separated.csv"

In [3]:
df = pd.read_csv(inputfile)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43848 entries, 0 to 43847
Data columns (total 37 columns):
datetime        43848 non-null object
target          41708 non-null float64
ELAMB_TEMP      43546 non-null float64
ELRAINFALL      43451 non-null float64
ELRH            43471 non-null float64
DLPM2.5         42496 non-null float64
LBPM2.5         41008 non-null float64
CHPM2.5         42455 non-null float64
MLPM2.5         42741 non-null float64
SSPM2.5         42727 non-null float64
TSPM2.5         42623 non-null float64
NTPM2.5         42506 non-null float64
ELPM2.5         41709 non-null float64
DLPM10          42722 non-null float64
LBPM10          42066 non-null float64
CHPM10          42834 non-null float64
MLPM10          42444 non-null float64
SSPM10          42755 non-null float64
TSPM10          42582 non-null float64
NTPM10          42870 non-null float64
ELPM10          42616 non-null float64
DLWIND_DIREC    43678 non-null float64
LBWIND_DIREC    43440 non-null float64
CHWIND_DIREC    43631 non-null float64
MLWIND_DIREC    43529 non-null float64
SSWIND_DIREC    43528 non-null float64
TSWIND_DIREC    43299 non-null float64
NTWIND_DIREC    43654 non-null float64
ELWIND_DIREC    43547 non-null float64
DLWIND_SPEED    43682 non-null float64
LBWIND_SPEED    43438 non-null float64
CHWIND_SPEED    43719 non-null float64
MLWIND_SPEED    43560 non-null float64
SSWIND_SPEED    43333 non-null float64
TSWIND_SPEED    43190 non-null float64
NTWIND_SPEED    43655 non-null float64
ELWIND_SPEED    43547 non-null float64
dtypes: float64(36), object(1)
memory usage: 12.4+ MB

In [5]:
for index, row in df.iterrows():
    for loc in locations:
        ws = row[loc+"WIND_SPEED"]
        if ws >= 0 and ws <= 0.3:
            df.set_value(index, loc+'WIND_SPEED', 0)
        elif ws >= 0.3 and ws < 1.6:
            df.set_value(index, loc+'WIND_SPEED', 1)
        elif ws >= 1.6 and ws < 3.4:
            df.set_value(index, loc+'WIND_SPEED', 2)
        elif ws >= 3.4 and ws < 5.5:
            df.set_value(index, loc+'WIND_SPEED', 3)
        elif ws >= 5.5 and ws < 8.0:
            df.set_value(index, loc+'WIND_SPEED', 4)
        elif ws >= 8.0 and ws < 10.8:
            df.set_value(index, loc+'WIND_SPEED', 5)
        elif ws >= 10.8 and ws < 13.9:
            df.set_value(index, loc+'WIND_SPEED', 6)
        elif ws >= 13.9 and ws < 17.2:
            df.set_value(index, loc+'WIND_SPEED', 7)
        elif ws >= 17.2 and ws < 20.8:
            df.set_value(index, loc+'WIND_SPEED', 8)
        elif ws >= 20.8 and ws < 24.5:
            df.set_value(index, loc+'WIND_SPEED', 9)
        elif ws >= 24.5 and ws < 28.5:
            df.set_value(index, loc+'WIND_SPEED', 10)
        elif ws >= 28.5 and ws < 32.6:
            df.set_value(index, loc+'WIND_SPEED', 11)
        elif ws >= 32.6 and ws < 37.0:
            df.set_value(index, loc+'WIND_SPEED', 12)
        else:
            pass
            #print 'WIND SPEED ERROR:', ws, 'INDEX:', index
    
        ws = row[loc+"WIND_DIREC"]
        if ws >= 0 and ws < 22.5:
            df.set_value(index, loc+'WIND_DIREC', 0)
        elif ws >= 22.5 and ws < 67.5:
            df.set_value(index, loc+'WIND_DIREC', 45)
        elif ws >= 67.5 and ws < 112.5:
            df.set_value(index, loc+'WIND_DIREC', 90)
        elif ws >= 112.5 and ws < 157.5:
            df.set_value(index, loc+'WIND_DIREC', 135)
        elif ws >= 157.5 and ws < 202.5:
            df.set_value(index, loc+'WIND_DIREC', 180)
        elif ws >= 202.5 and ws < 247.5:
            df.set_value(index, loc+'WIND_DIREC', 225)
        elif ws >= 247.5 and ws < 292.5:
            df.set_value(index, loc+'WIND_DIREC', 270)
        elif ws >= 292.5 and ws < 337.5:
            df.set_value(index, loc+'WIND_DIREC', 315)
        elif ws >= 337.5 and ws <= 360:
            df.set_value(index, loc+'WIND_DIREC', 0)
        else:
            pass
            #print 'WIND DIREC ERROR:', ws, 'INDEX:', index

In [ ]:
'''
    ws = row["RAINFALL"]
    if ws == 0:
        df.set_value(index, 'RAINFALL', 0)
    elif ws > 0 and ws <= 2.5:
        df.set_value(index, 'RAINFALL', 1)
    elif ws > 2.5 and ws <= 8:
        df.set_value(index, 'RAINFALL', 2)
    elif ws > 8 and ws <= 40:
        df.set_value(index, 'RAINFALL', 3)
    else:
        df.set_value(index, 'RAINFALL', 4)
        
    ws = row["RH"]
    if ws <= 40:
        df.set_value(index, 'RH', 0)
    elif ws > 40 and ws <= 60:
        df.set_value(index, 'RH', 1)
    elif ws > 60 and ws <= 80:
        df.set_value(index, 'RH', 2)
    elif ws > 80 and ws <= 100:
        df.set_value(index, 'RH', 3)
    else:
        print 'RH ERROR:', ws, 'INDEX:', index
'''

In [7]:
df.head()

,datetime,target,ELAMB_TEMP,ELRAINFALL,ELRH,DLPM2.5,LBPM2.5,CHPM2.5,MLPM2.5,SSPM2.5,...,NTWIND_DIREC,ELWIND_DIREC,DLWIND_SPEED,LBWIND_SPEED,CHWIND_SPEED,MLWIND_SPEED,SSWIND_SPEED,TSWIND_SPEED,NTWIND_SPEED,ELWIND_SPEED
0,2012-01-01 00:00:00,43.0,15.0,0.0,77.0,18.0,NaN,28.0,19.0,26.0,...,315.0,45.0,1.0,2.0,2.0,3.0,4.0,5.0,1.0,3.0
1,2012-01-01 01:00:00,60.0,15.0,0.0,75.0,17.0,NaN,32.0,24.0,23.0,...,315.0,45.0,1.0,3.0,2.0,3.0,3.0,5.0,1.0,3.0
2,2012-01-01 02:00:00,55.0,16.0,0.0,74.0,25.0,NaN,NaN,27.0,22.0,...,45.0,45.0,2.0,2.0,2.0,3.0,4.0,5.0,1.0,3.0
3,2012-01-01 03:00:00,41.0,16.0,0.0,73.0,33.0,NaN,22.0,27.0,23.0,...,315.0,45.0,1.0,3.0,2.0,3.0,4.0,5.0,1.0,3.0
4,2012-01-01 04:00:00,31.0,15.0,0.0,74.0,33.0,NaN,22.0,27.0,25.0,...,45.0,45.0,1.0,3.0,2.0,3.0,3.0,5.0,1.0,3.0

In [8]:
df.to_csv(outputfile, index=False)