# Load Data

In [1]:
#coding="big5"

#version 1.0
#2017/5/22

In [2]:
import pandas as pd
import numpy as np

inputfile = "../data/reshaped.csv"
outputfile = "../data/remove_marks.csv"

In [3]:
df = pd.read_csv(inputfile, encoding="big5")
station = df["station"][1]
print 'station:', station

station: 二林

In [4]:
columns = df.columns
for column in columns:
    df[column] = df[column].str.replace('*', '').str.replace('#', '').str.replace('x', '')

In [5]:
if 'station' in df.columns:
    df = df.drop('station',1)
    #df.info()

In [6]:
df = df.apply(pd.to_numeric, errors='ignore', downcast='float')

# Operations

In [7]:
main = df.copy()

In [8]:
mask = (main < 0)
main = main.where(~mask, np.nan)
main[main.isnull().T.any()]

,datetime,AMB_TEMP,CO,NO,NO2,NOx,O3,PM10,PM2.5,RAINFALL,RH,SO2,WD_HR,WIND_DIREC,WIND_SPEED,WS_HR
0,2016-01-01 00:00:00,16.0,0.61,NaN,14.0,14.0,32.0,107.0,66.0,0.0,76.0,5.0,47.0,54.0,1.7,1.4
131,2016-01-06 11:00:00,21.0,0.25,3.9,12.0,16.0,27.0,0.0,NaN,0.0,86.0,3.7,41.0,41.0,3.1,2.8
323,2016-01-14 11:00:00,19.0,0.56,2.6,12.0,14.0,42.0,0.0,NaN,0.0,65.0,1.3,67.0,84.0,4.0,5.0
421,2016-01-18 13:00:00,19.0,0.70,2.4,17.0,19.0,52.0,0.0,NaN,0.0,63.0,8.2,75.0,81.0,5.9,2.4
587,2016-01-25 11:00:00,13.0,0.25,1.5,6.8,8.3,41.0,0.0,NaN,0.0,51.0,2.6,40.0,44.0,5.5,5.2
596,2016-01-25 20:00:00,10.0,0.33,NaN,15.0,14.0,25.0,52.0,27.0,0.0,71.0,3.1,50.0,54.0,4.3,3.2
597,2016-01-25 21:00:00,10.0,0.36,NaN,16.0,16.0,23.0,45.0,25.0,0.0,71.0,3.5,41.0,39.0,4.3,3.8
599,2016-01-25 23:00:00,10.0,0.38,NaN,17.0,17.0,21.0,47.0,28.0,0.0,73.0,4.0,38.0,34.0,3.6,3.6
602,2016-01-26 02:00:00,9.3,0.37,NaN,18.0,18.0,17.0,48.0,31.0,0.0,78.0,3.8,40.0,40.0,2.7,2.5
662,2016-01-28 14:00:00,19.0,0.51,3.9,19.0,23.0,27.0,NaN,NaN,0.2,88.0,7.1,56.0,178.0,5.1,0.5
757,2016-02-01 13:00:00,18.0,0.38,2.4,9.6,12.0,39.0,0.0,NaN,0.2,75.0,2.3,45.0,53.0,7.1,6.1
858,2016-02-05 18:00:00,14.0,0.32,NaN,6.6,6.6,43.0,42.0,25.0,0.0,79.0,1.6,44.0,43.0,7.8,7.2
864,2016-02-06 00:00:00,15.0,0.51,NaN,6.7,6.6,59.0,44.0,31.0,0.0,78.0,2.6,38.0,38.0,7.3,6.6
995,2016-02-11 11:00:00,21.0,0.40,2.9,16.0,19.0,40.0,0.0,NaN,0.0,64.0,1.3,324.0,342.0,1.7,1.0
1073,2016-02-14 17:00:00,16.0,0.40,1.8,7.4,9.2,23.0,34.0,10.0,0.0,80.0,NaN,41.0,54.0,5.9,5.4
1143,2016-02-17 15:00:00,18.0,0.35,1.7,17.0,19.0,0.0,NaN,NaN,0.0,59.0,6.5,313.0,250.0,3.7,0.3
1169,2016-02-18 17:00:00,17.0,0.40,0.8,16.0,17.0,38.0,0.0,NaN,0.0,84.0,5.2,68.0,55.0,2.7,1.5
1260,2016-02-22 12:00:00,20.0,0.35,2.6,6.3,8.9,57.0,0.0,NaN,0.0,71.0,2.5,326.0,312.0,3.5,1.3
1453,2016-03-01 13:00:00,20.0,0.30,0.9,7.2,8.2,71.0,0.0,NaN,0.0,49.0,3.9,61.0,309.0,5.1,1.3
1694,2016-03-11 14:00:00,14.0,0.29,1.1,14.0,15.0,27.0,0.0,NaN,0.0,81.0,1.6,28.0,30.0,5.4,5.3
1700,2016-03-11 20:00:00,13.0,0.34,NaN,15.0,15.0,24.0,40.0,24.0,0.2,89.0,1.3,31.0,31.0,2.5,2.7
1701,2016-03-11 21:00:00,13.0,0.35,NaN,13.0,13.0,24.0,39.0,29.0,0.0,89.0,1.6,30.0,33.0,2.8,2.4
1702,2016-03-11 22:00:00,13.0,0.36,NaN,13.0,12.0,23.0,23.0,27.0,0.0,88.0,1.5,31.0,28.0,2.6,2.5
1703,2016-03-11 23:00:00,13.0,0.38,NaN,13.0,13.0,22.0,24.0,24.0,0.0,88.0,2.2,34.0,30.0,2.4,2.9
1704,2016-03-12 00:00:00,13.0,0.38,NaN,12.0,12.0,21.0,32.0,21.0,0.0,88.0,0.8,33.0,37.0,2.7,2.4
1790,2016-03-15 14:00:00,15.0,0.67,5.6,35.0,41.0,12.0,0.0,NaN,0.0,90.0,5.7,36.0,0.0,0.0,1.7
1954,2016-03-22 10:00:00,19.0,0.39,1.6,8.9,10.0,42.0,0.0,NaN,0.0,90.0,1.5,56.0,52.0,3.5,2.2
1961,2016-03-22 17:00:00,18.0,0.27,0.3,12.0,12.0,45.0,94.0,56.0,0.0,90.0,NaN,25.0,25.0,2.3,2.7
1962,2016-03-22 18:00:00,18.0,0.35,NaN,13.0,13.0,38.0,89.0,48.0,0.0,91.0,0.5,67.0,110.0,2.9,1.7
1978,2016-03-23 10:00:00,19.0,0.77,21.0,24.0,45.0,5.3,NaN,NaN,0.8,94.0,3.9,62.0,56.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7635,2016-11-14 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,159.0,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7636,2016-11-14 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,163.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7637,2016-11-14 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN,138.0,54.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7643,2016-11-14 11:00:00,30.0,0.46,0.2,8.5,8.8,77.0,0.0,NaN,0.0,62.0,0.2,315.0,292.0,2.0,0.7
7645,2016-11-14 13:00:00,29.0,0.34,NaN,5.7,5.3,82.0,133.0,37.0,0.0,66.0,3.3,289.0,296.0,2.8,2.7
7646,2016-11-14 14:00:00,29.0,0.28,NaN,4.9,4.7,75.0,113.0,24.0,0.0,67.0,3.0,307.0,302.0,3.2,2.6
7647,2016-11-14 15:00:00,28.0,0.25,NaN,3.7,3.5,70.0,82.0,37.0,0.0,68.0,2.7,314.0,312.0,3.1,2.8
7648,2016-11-14 16:00:00,27.0,0.27,NaN,3.9,3.8,66.0,53.0,26.0,0.0,70.0,1.7,317.0,51.0,2.6,0.7
7650,2016-11-14 18:00:00,25.0,0.36,NaN,9.1,9.1,50.0,63.0,25.0,0.0,78.0,2.6,6.0,322.0,1.0,0.4
7651,2016-11-14 19:00:00,25.0,0.47,NaN,11.0,11.0,44.0,84.0,38.0,0.0,84.0,2.8,319.0,324.0,1.0,0.7
7652,2016-11-14 20:00:00,25.0,0.61,NaN,13.0,13.0,42.0,105.0,53.0,0.0,86.0,3.9,41.0,109.0,0.7,0.3
7653,2016-11-14 21:00:00,24.0,0.73,NaN,13.0,13.0,30.0,121.0,62.0,0.0,88.0,4.0,78.0,287.0,0.5,0.2
7655,2016-11-14 23:00:00,23.0,0.60,NaN,13.0,13.0,24.0,135.0,73.0,0.0,91.0,3.9,294.0,314.0,0.5,0.7
7727,2016-11-17 23:00:00,24.0,0.22,NaN,10.0,10.0,19.0,56.0,11.0,0.0,92.0,3.4,312.0,15.0,0.9,0.5
7864,2016-11-23 16:00:00,22.0,0.03,1.6,18.0,19.0,22.0,0.0,NaN,0.2,91.0,3.0,38.0,44.0,3.9,4.1
7886,2016-11-24 14:00:00,24.0,0.31,1.9,NaN,0.9,37.0,0.0,NaN,0.0,69.0,3.2,53.0,43.0,6.1,4.4
7978,2016-11-28 10:00:00,22.0,0.27,1.8,10.0,12.0,40.0,0.0,NaN,0.0,67.0,2.0,41.0,38.0,4.7,3.8
8086,2016-12-02 22:00:00,21.0,0.27,NaN,13.0,13.0,27.0,38.0,12.0,0.0,83.0,4.2,38.0,39.0,3.6,4.0
8088,2016-12-03 00:00:00,20.0,0.20,NaN,13.0,13.0,24.0,21.0,2.0,0.0,84.0,4.6,37.0,38.0,4.0,3.5
8170,2016-12-06 10:00:00,22.0,0.42,1.5,15.0,16.0,40.0,0.0,NaN,0.0,58.0,5.1,40.0,39.0,6.7,5.9
8314,2016-12-12 10:00:00,23.0,0.30,3.4,12.0,16.0,33.0,0.0,NaN,0.0,77.0,6.8,323.0,113.0,4.2,0.8
8315,2016-12-12 11:00:00,24.0,0.22,2.1,8.4,11.0,38.0,70.0,NaN,0.0,74.0,3.7,308.0,279.0,4.6,0.6
8483,2016-12-19 11:00:00,25.0,0.30,3.3,14.0,18.0,40.0,0.0,NaN,0.0,66.0,6.6,37.0,29.0,2.6,1.0
8490,2016-12-19 18:00:00,21.0,0.71,NaN,12.0,12.0,36.0,246.0,148.0,0.0,90.0,4.8,298.0,348.0,1.9,0.3
8491,2016-12-19 19:00:00,21.0,0.33,NaN,9.9,9.3,38.0,249.0,144.0,0.0,92.0,6.3,44.0,44.0,1.8,0.6
8492,2016-12-19 20:00:00,21.0,0.25,NaN,8.8,8.4,31.0,107.0,66.0,0.0,93.0,4.4,55.0,43.0,1.3,1.1
8493,2016-12-19 21:00:00,21.0,0.30,NaN,9.1,8.8,26.0,75.0,24.0,0.0,93.0,3.5,350.0,300.0,0.9,0.4
8494,2016-12-19 22:00:00,20.0,0.31,NaN,11.0,10.0,19.0,62.0,22.0,0.0,94.0,2.8,29.0,56.0,0.6,0.2
8524,2016-12-21 04:00:00,22.0,0.26,NaN,7.9,7.9,24.0,120.0,35.0,0.0,95.0,2.5,181.0,160.0,2.1,1.8
8680,2016-12-27 16:00:00,18.0,0.33,107.0,NaN,11.0,26.0,0.0,NaN,0.0,72.0,1.5,37.0,37.0,12.0,10.0

In [9]:
main.to_csv(outputfile, index=False)

# Useful functions

df[df.isnull().T.sum() > 0]
df.loc[index]
test[column][test[column] < 0] = 0

# Testing

In [10]:
test = df.copy()